Fix test
> rollup-tree rollupAllTheThings does not include rollup deps and just returns root tree via super when addon is not the top addon:
     TypeError: output.readDir is not a function

and missing rollupEntry